services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8087:8000"
    volumes:
      - ./data:/app/data
      - app-cache:/app/.cache
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - APP_TIMEZONE=America/Sao_Paulo

volumes:
  app-cache:
